In [1]:
import numpy as np
from GenerateData import GenerateData
from GenerateData import GenerateProbability
from HMMfunctions import HMM_Function
from HMMfunctions import HMMReestimation

In [2]:
NumState = 3
NumColorBall = 3 #fixed with red, blue, yellow
redID = 0
blueID = 1
yellowID = 2

In [3]:
genProb = GenerateProbability(NumState, NumColorBall)
pi = genProb.genProbStateBegin()
B = genProb.genProbBallColor()
A = genProb.genProbState()
print("pi:\n",pi[0])
print("A:\n",A)
print("B:\n",B)

pi:
 [0.31 0.33 0.36]
A:
 [[0.41 0.3  0.29]
 [0.36 0.25 0.39]
 [0.28 0.4  0.32]]
B:
 [[0.34 0.31 0.35]
 [0.32 0.34 0.34]
 [0.33 0.41 0.26]]


In [4]:
observation_str = np.array([redID, blueID, yellowID, redID])
mrk = HMM_Function(pi, A, B, observation_str)

In [5]:
mrk.calculate_Problem1()

[[0.1054 0.1056 0.1188]]
[[0.03549314 0.0358836  0.04500406]]
[[0.014025   0.01279096 0.01005912]]
[[0.00447833 0.00365724 0.00405063]]


0.012186200732295404

In [6]:
mrk.calculate_Problem2()

[[0.1054     0.01339634 0.00203576 0.00028378]
 [0.1056     0.0161568  0.00229642 0.0002097 ]
 [0.1188     0.01688544 0.0016383  0.00029555]]
[[0 0 1 0]
 [0 2 2 2]
 [0 1 1 1]]


[1, 2, 1, 0]

In [13]:
tmp = GenerateData(pi, A, B)
observation = tmp.generateRandomData(100)

=====Starting...=====
At state:  0
Pick ball:  red
=====Started========
At state:  1
Pick ball:  blue
At state:  0
Pick ball:  red
At state:  0
Pick ball:  red
At state:  1
Pick ball:  blue
At state:  0
Pick ball:  red
At state:  1
Pick ball:  blue
At state:  1
Pick ball:  blue
At state:  2
Pick ball:  red
At state:  0
Pick ball:  red
At state:  2
Pick ball:  red
At state:  2
Pick ball:  red
At state:  0
Pick ball:  red
At state:  1
Pick ball:  blue
At state:  1
Pick ball:  yellow
At state:  2
Pick ball:  red
At state:  2
Pick ball:  red
At state:  0
Pick ball:  red
At state:  2
Pick ball:  red
At state:  1
Pick ball:  yellow
At state:  2
Pick ball:  red
At state:  1
Pick ball:  blue
At state:  0
Pick ball:  red
At state:  0
Pick ball:  red
At state:  0
Pick ball:  red
At state:  1
Pick ball:  blue
At state:  1
Pick ball:  blue
At state:  0
Pick ball:  red
At state:  0
Pick ball:  red
At state:  1
Pick ball:  yellow
At state:  2
Pick ball:  red
At state:  2
Pick ball:  red
At state:  1

In [19]:
opt = HMMReestimation(A, B, pi, NumState, NumColorBall, observation)
NSteps = 1000000
epsilon = 0.0000000001
opt.fit(NSteps, epsilon)

Reesimattion done at step = 1905
A: 
 [[0.7659 0.     0.2341]
 [0.6808 0.2273 0.0919]
 [0.     0.9902 0.0098]]
B: 
 [[0.8701 0.     0.1299]
 [0.     1.     0.    ]
 [1.     0.     0.    ]]
pi: 
 [0. 0. 1.]
