In [1]:
import numpy as np
from GenerateData import GenerateData
from GenerateData import GenerateProbability
from HMMfunctions import HMM_Function
from HMMfunctions import HMMReestimation

In [2]:
NumState = 3
NumColorBall = 3 #fixed with red, blue, yellow
redID = 0
blueID = 1
yellowID = 2

In [3]:
genProb = GenerateProbability(NumState, NumColorBall)
pi = genProb.genProbStateBegin()
B = genProb.genProbBallColor()
A = genProb.genProbState()
print("pi:\n",pi[0])
print("A:\n",A)
print("B:\n",B)

pi:
 [0.35 0.36 0.29]
A:
 [[0.3  0.36 0.34]
 [0.4  0.25 0.35]
 [0.31 0.27 0.42]]
B:
 [[0.39 0.31 0.3 ]
 [0.29 0.3  0.41]
 [0.31 0.4  0.29]]


In [4]:
observation_str = np.array([redID, blueID, yellowID, redID])
mrk = HMM_Function(pi, A, B, observation_str)

In [5]:
mrk.calculate_Problem1()

[[0.1365 0.1044 0.0899]]
[[0.03427949 0.0298539  0.0482832 ]]
[[0.01115796 0.01346463 0.01229102]]
[[0.00489195 0.00310346 0.00423725]]


0.012232663523103596

In [6]:
mrk.calculate_Problem2()

[[0.1365     0.0129456  0.00176904 0.00032059]
 [0.1044     0.014742   0.00205503 0.00018469]
 [0.0899     0.018564   0.0022611  0.00029439]]
[[0 1 1 1]
 [0 0 2 0]
 [0 0 2 2]]


[1, 2, 0, 0]

In [7]:
tmp = GenerateData(pi, A, B)
observation = tmp.generateRandomData(100)

=====Starting...=====
At state:  1
Pick ball:  red
=====Started========
At state:  0
Pick ball:  blue
At state:  1
Pick ball:  yellow
At state:  0
Pick ball:  yellow
At state:  2
Pick ball:  blue
At state:  1
Pick ball:  red
At state:  0
Pick ball:  yellow
At state:  0
Pick ball:  red
At state:  1
Pick ball:  yellow
At state:  0
Pick ball:  blue
At state:  0
Pick ball:  yellow
At state:  1
Pick ball:  red
At state:  2
Pick ball:  blue
At state:  2
Pick ball:  red
At state:  2
Pick ball:  yellow
At state:  0
Pick ball:  yellow
At state:  0
Pick ball:  yellow
At state:  0
Pick ball:  red
At state:  0
Pick ball:  red
At state:  0
Pick ball:  blue
At state:  2
Pick ball:  yellow
At state:  0
Pick ball:  yellow
At state:  2
Pick ball:  yellow
At state:  1
Pick ball:  red
At state:  2
Pick ball:  blue
At state:  1
Pick ball:  red
At state:  2
Pick ball:  red
At state:  0
Pick ball:  yellow
At state:  1
Pick ball:  blue
At state:  2
Pick ball:  red
At state:  2
Pick ball:  red
At state:  0
Pi

In [8]:
opt = HMMReestimation(A, B, pi, NumState, NumColorBall, observation)
NSteps = 1000000
epsilon = 0.0000000001
opt.fit(NSteps, epsilon)

Reesimattion done at step = 2922
A: 
 [[0.3243 0.2112 0.4644]
 [0.2614 0.3691 0.3695]
 [0.4426 0.1371 0.4203]]
B: 
 [[1.     0.     0.    ]
 [0.     0.     1.    ]
 [0.     0.8691 0.1309]]
pi: 
 [1. 0. 0.]
